# fly.toml file generated for aversions on 2023-03-15T23:16:06-07:00

app = "aversions"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_URL = "https://aversions.fly.dev"
  DB_CONNECTION = "mysql"
  DB_HOST = "aversions-mysql.internal"
  DB_DATABASE= "aversions"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  BANDCAMP_BASE_URL = "https://aversionsband.bandcamp.com/"
  SOUNDCLOUD_BASE_URL = "https://soundcloud.com/aversionstheband/"
  YOUTUBE_BASE_URL = "https://www.youtube.com/watch?v="
  FILESYSTEM_DRIVER = "s3"
  AWS_DEFAULT_REGION = "us-west-2"
  AWS_BUCKET = "aversionswebsitebucket"
  AWS_URL = "https://aversionswebsitebucket.s3.us-west-2.amazonaws.com"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
